services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: autosendr
      POSTGRES_USER: autosendr_user
      POSTGRES_PASSWORD: autosendr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - autosendr_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autosendr_user -d autosendr"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://autosendr_user:autosendr_password@db:5432/autosendr
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - autosendr_network
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data:/app/uploads

volumes:
  postgres_data:
  uploads_data:

networks:
  autosendr_network:
    driver: bridge
